//
//  UserInputFieldManager.swift
//  BagCam
//
//  Created by Kevin Shah on 12/02/21.
//

import UIKit

/// UserInputFieldType
enum UserInputFieldType {
    case login
    case signup
    case forgotPassword
    case forgotPasswordSub
    case verifyCode
    
    var titleAttr: NSAttributedString? {
        switch self {
        case .login:
            let attStr: NSAttributedString = NSAttributedString(string: "Welcome back,\nsign in.", attributes: [.font: UIFont.systemFont(ofSize: 45, weight: .medium)])
            return attStr
        case .signup:
            let attStr: NSAttributedString = NSAttributedString(string: "Hey there,\nsign up.", attributes: [.font: UIFont.systemFont(ofSize: 45, weight: .medium)])
            return attStr
        case .forgotPassword:
            let attStr: NSAttributedString = NSAttributedString(string: "Password\nRecovery.", attributes: [.font: UIFont.systemFont(ofSize: 45, weight: .medium)])
            return attStr
        case .forgotPasswordSub:
            let attStr: NSAttributedString = NSAttributedString(string: "Please enter your email address and we will send you an email with further instructions to reset your password.", attributes: [.font: AppFont.mabryProRegular.of(17)])
            return attStr
        case .verifyCode:
            let attStr: NSAttributedString = NSAttributedString(string: "Please enter the security code generated by your mobile authenticator app.", attributes: [.font: AppFont.mabryProRegular.of(17)])
            return attStr
        }
    }
}

/// UserInputFieldModel
class UserInputFieldModel: NSObject {
    
    var title: String = ""
    var placeholder: String = ""
    var text: String = ""
    var webKey: String = ""
}

/// UserInputFieldManager
class UserInputFieldManager: NSObject {
    
    /// Variable Declaration(s)
    var arrUserInputFieldModel: [UserInputFieldModel] = []
    var type: UserInputFieldType = .login
    
    init(_ type: UserInputFieldType) {
        self.type = type
        super.init()
        self.prepareUserInputFieldData()
    }
    
    fileprivate func prepareUserInputFieldData() {
        switch self.type {
        case .login:
            self.loginField()
        case .signup:
            self.signupField()
        case .forgotPassword:
            self.forgotPasswordField()
        case .verifyCode:
            self.verifyCodeField()
        default:
            break
        }
    }
    
    fileprivate func loginField() {
        let inputField1 = UserInputFieldModel()
        inputField1.title = "Email Address".uppercased()
        inputField1.placeholder = "user@bagcam.com"
        inputField1.webKey = "email"
        
        let inputField2 = UserInputFieldModel()
        inputField2.title = "Password".uppercased()
        inputField2.placeholder = "123456"
        inputField2.webKey = "password"
        
        self.arrUserInputFieldModel = [inputField1, inputField2]
    }
    
    fileprivate func signupField() {
        let inputField1 = UserInputFieldModel()
        inputField1.title = "Email Address".uppercased()
        inputField1.placeholder = "user@bagcam.com"
        inputField1.webKey = "email"
        
        let inputField2 = UserInputFieldModel()
        inputField2.title = "Password".uppercased()
        inputField2.placeholder = "123456"
        inputField2.webKey = "password"
        
        let inputField3 = UserInputFieldModel()
        inputField3.title = "Retype Password".uppercased()
        inputField3.placeholder = "123456"
        inputField3.webKey = "retype_password"
        
        self.arrUserInputFieldModel = [inputField1, inputField2, inputField3]
    }
    
    fileprivate func forgotPasswordField() {
        let inputField1 = UserInputFieldModel()
        inputField1.title = "Email Address".uppercased()
        inputField1.placeholder = "user@bagcam.com"
        inputField1.webKey = "email"
        
        self.arrUserInputFieldModel = [inputField1]
    }
    
    fileprivate func verifyCodeField() {
        let inputField1 = UserInputFieldModel()
        inputField1.title = "Code".uppercased()
        inputField1.placeholder = "6-digit code"
        inputField1.webKey = "code"
        
        self.arrUserInputFieldModel = [inputField1]
    }
}

// MARK: - Other Method(s)
extension UserInputFieldManager {
    
    func paramDict() -> [String : Any] {
        var dictParam = [String: Any]()
        arrUserInputFieldModel.forEach { (inputField) in
            if !inputField.webKey.isEmpty {
                dictParam[inputField.webKey] = inputField.text.trimmingCharacters(in: .whitespacesAndNewlines)
            }
        }
        return dictParam
    }
    
    func isValidData() -> (valid: Bool, error: String) {
        var result = (valid: true, error: "")
        switch type {
        case .login:
            if String.validate(value: arrUserInputFieldModel[0].text) {
                result.valid = false
                result.error = kEnterEmail
                return result
            } else if !arrUserInputFieldModel[0].text.isEmailAddressValid {
                result.valid = false
                result.error = kEnterValidEmail
                return result
            } else if String.validate(value: arrUserInputFieldModel[1].text) {
                result.valid = false
                result.error = kEnterPassword
                return result
            } else if !arrUserInputFieldModel[1].text.isPasswordValid {
                result.valid = false
                result.error = kEnterValidPassword
                return result
            }
        default:
            break
        }
        return result
    }
}
